package com.darion.kpi.kpis;

public enum KpiId {
    EVENT_TYPE_BREAKDOWN,
    EVENTS_PER_HOUR,
    EVENTS_PER_HOUR_BY_TYPE,
    ERROR_RATE_PER_HOUR,
    DURATION_STATS_PER_HOUR,
    SUCCESS_RATE,
    TOP_ACTORS,
    SITE_VOLUME_AND_SUCCESS,
    UNIQUE_ACTORS_PER_HOUR,
    UNIQUE_SESSIONS_PER_HOUR,
    SUCCESS_RATE_BY_EVENT_TYPE,
    DURATION_STATS_BY_EVENT_TYPE,
    TOP_SESSIONS_BY_EVENT_COUNT,
    TOP_EVENT_TYPES,

}
